# WARNINGS = -Wall -Wextra -Wpedantic -Wconversion -Wfloat-equal -Wformat-nonliteral -Wformat-security -Wformat-y2k -Wformat=2 -Wimport -Winvalid-pch -Wlogical-op -Wmissing-field-initializers -Wmissing-format-attribute -Wmissing-include-dirs -Wmissing-noreturn -Wpacked -Wpointer-arith -Wredundant-decls -Wshadow -Wstack-protector -Wstrict-null-sentinel -Wswitch-enum -Wundef -Wwrite-strings -Wdisabled-optimization -Wsign-conversion -Wsign-promo -Wstrict-aliasing=2 -Wstrict-overflow=5 -Wunused -Wunused-parameter
# -Wmissing-declarations -Wpadded -Werror 

all:
	c++ -std=c++17 $(WARNINGS) -Iinclude/ src/findroot.cc -o findroot

